apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsportal-api
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{ version }}
  port: 8080
  liveness:
    path: /permitteringsportal-api/internal/isAlive
  readiness:
    path: /permitteringsportal-api/internal/isReady
  gcp:
    sqlInstances:
      - name: permitteringsportal-api
        type: POSTGRES_12
        databases:
          - name: permitteringsportal-api-db
            envVarPrefix: DATABASE
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: permitteringsportal
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
        - application: notifikasjon-produsent-api
          namespace: arbeidsgiver

  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
