apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsportal-api
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{ version }}
  port: 8080
  ingresses:
  {{#each ingress as |url|}}
      - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  gcp:
    sqlInstances:
      - name: permitteringsportal-api
        type: POSTGRES_12
        databases:
          - name: permitteringsportal-api-db
            envVarPrefix: DATABASE
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: permitteringsportal
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
  kafka:
    pool: nav-dev
