/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.permitteringsportal

class App {
    fun start() {
        println("starter app")
    }

}

fun main() {
    App().start()

}
